version: '3.8'
services:
  api:
    restart: always
    build: .
    ports:
      - ${NODE_APP_PORT}:${NODE_APP_PORT}
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  db:
    image: mysql
    ports:
      - '3306:${DATABASE_PORT}'
    volumes:
      - data:/var/lib/mysql
    environment:
        - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD}
        - MYSQL_DATABASE=${DATABASE_NAME}
        - MYSQL_USER=${DATABASE_USERNAME}
        - MYSQL_PASSWORD=${DATABASE_PASSWORD}

volumes:
  data: {}
